### PR TITLE
fix install.sh

### PR DESCRIPTION
**Pull request by PapillonMcGill**
## Brief summary of changes
fix some error in tools/install.sh identified by shellcheck

### CODE REVIEW

**Comment by PapillonMcGill** [comment]
@gdevenyi  The only failures left are in node_modules/ and vendor/ directories.

Do you prefer to pursue with this shellcheck PR or should I send these modifications to a separate PR directly on Loris?

**Comment by gdevenyi** [comment]
I'll handle it with the shellcheck PR.

**Comment by gdevenyi** [comment]
P.S. this PR is against my repo instead of aces/Loris. Not sure that's intended.

**Comment by PapillonMcGill** [comment]
Yes, I wanted to contribute to fixing errors reported by your PR (in aces/loris). 
As Travis still report errors on vendors files, not sure if you want to continue with your PR or close it.

One draw back from this method is that I won't be able to approve your PR (in aces/loris).
Probably better that I submit a PR directly in aces/loris and it get merge before your's so Travis pass and we can approve each other's PR.

**Comment by gdevenyi** [comment]
:+1: I think fixing up the bugs in Loris until my shellcheck PR passes is the right way to go, I'll sort out the vendor thing.

**Pull request closed without merging**
